# django-core-utils travis config file
# TODO: change email address

language: python


sudo: false

python: '2.7'

env:
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110

matrix:
  fast_finish: true
  include:
    - python: '3.5'
      env: TOX_ENV=py35-django19
    - python: '3.5'
      env: TOX_ENV=py35-django110

       
install:
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  email:
    recipients:
      - amnon.janiv@ondalear.com

    on_success: change
    on_failure: always
  
branches:
  only:
    - master
    - develop