# django-core-utils travis config file
# TODO: change email address

language: python


sudo: false

python: '3.6'

env:
  - TOX_ENV=py36-django112
  - TOX_ENV=py36-django210

matrix:
  fast_finish: true
  include:
    - python: '2.7'
      env: TOX_ENV=py27-django112
    - python: 2.7
      env: TOXENV=py27-django210
    - python: '3.5'
      env: TOX_ENV=py35-django112
    - python: '3.5'
      env: TOX_ENV=py35-django210
    - python: 3.7
      env: TOXENV=py37-django210
      dist: xenial
      sudo: true


install:
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  email:
    recipients:
      - amnon.janiv@ondalear.com

    on_success: change
    on_failure: always
  
branches:
  only:
    - master
    - develop